### ISSUE TITLE
Add PostCSS nesting

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/netlify-js-app#528]
Install [`postcss-nesting`](https://www.npmjs.com/package/postcss-nesting).

`npm install postcss-nesting --save`

This will allow for things like:

```css
.btn {
  background-color: var(--bg);
  &:hover {
    background-color: var(--bg-hover);
  }
}
```
